# id: 353928ae-dd88-46c6-8ea8-5e42952cc97b
# opnrvn-r-25
ruleId: aws-management-tools-cloudtrail-ensure-log-metric-filter-and-alarm-exist-for-aws-config-changes
type: asset
ruleName: >
  Ensure a log metric filter and alarm exist for AWS Config configuration changes
description: >
  Real-time monitoring of API calls can be achieved by directing CloudTrail Logs to
  CloudWatch Logs and establishing corresponding metric filters and alarms. It is
  recommended that a metric filter and alarm be established for detecting changes to
  CloudTrail's configurations.
severity: high
enabled: true
sql: >
  WITH
  get_group_names AS (
    SELECT log_group_name
     FROM
      (SELECT arn,
          jsonb_array_elements(supplementaryconfiguration->'eventSelectors'->'eventSelectors') AS event_selector,
          regexp_replace(regexp_replace(supplementaryconfiguration->'trailDetails'->'trail'->>'cloudWatchLogsLogGroupArn', '.*log-group:', ''), ':\*', '') AS log_group_name
      FROM magpie.awscloudtrailtrail
      WHERE resourcetype = 'AWS::CloudTrail::Trail' AND supplementaryconfiguration->'trailDetails'->'trail'->'isMultiRegionTrail' = 'true' AND supplementaryconfiguration->'status'->'isLogging' = 'true') get_log_group_name_table
    WHERE event_selector->'includeManagementEvents' = 'true' AND event_selector->>'readWriteType' = 'All'
  ),
  get_metric_filters AS (
    SELECT jsonb_array_elements(configuration->'metricTransformations') AS metric
    FROM magpie.awswatchlogsmetricfilter AS metric_filters, get_group_names
    WHERE metric_filters.resourcetype = 'AWS::CloudWatchLogs::MetricFilter' AND metric_filters.configuration->>'logGroupName' = get_group_names.log_group_name
      AND regexp_replace(metric_filters.configuration->>'filterPattern', '\s', '', 'g') LIKE regexp_replace('%' || ' ($.eventSource = config.amazonaws.com) &&
                                                                                                      (($.eventName=StopConfigurationRecorder)||($.eventName=DeleteDeliveryChannel)||
                                                                                                      ($.eventName=PutDeliveryChannel)||($.eventName=PutConfigurationRecorder))' || '%', '\s', '', 'g')
  ),
  get_alarm_topic AS (
    SELECT regexp_replace(jsonb_array_elements_text(configuration->'alarmActions'), '\"', '', 'g') AS topic_arn
    FROM magpie.awswatchalarm AS alarms, get_metric_filters
    WHERE alarms.resourcetype = 'AWS::CloudWatch::Alarm' AND alarms.configuration->>'metricName' = get_metric_filters.metric->>'metricName'
  ),
  get_topic_subscribers_confirmed AS (
    SELECT awssnstopic.configuration->'attributes'->>'SubscriptionsConfirmed' AS subscribers_number
    FROM get_alarm_topic, magpie.awssnstopic AS awssnstopic
    WHERE awssnstopic.resourcetype='AWS::SNS::Topic' AND get_alarm_topic.topic_arn = awssnstopic.arn
  )

  SELECT 'No log metric filter and alarm exist for AWS Config configuration changes' AS asset_id
  WHERE NOT EXISTS
      (SELECT *
       FROM get_group_names)
    OR NOT EXISTS
      (SELECT *
       FROM get_metric_filters)
    OR EXISTS
      (SELECT *
       FROM get_topic_subscribers_confirmed
       WHERE subscribers_number = '0');
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 0.9
